<?php
$data = $_GET['data'];
include 'conn_oracle.php';
try {
    if (!$stmt = oci_parse($oraConn, "SELECT TBDOCTONFCE.NROEMPRESA LOJA,
TBDOCTONFCE.DTAMOVIMENTO,
TBDOCTONFCE.VLRDOCTONFCE VLR_PDV,
TBMFLDOCTOFISCAL.VLRDOCTOFISCAL VLR_ABC,
NVL(TBFISCAL.VLRFISCAL,0) VLR_FISCAL,
NVL(TBTESOURARIA.Vlr_Tesouraria,0) VLR_TES,
NVL(TBFISCALAUX.VLRFISCAL,0) DIF_FISCAL_AUX,
NVL((TBDOCTONFCE.VLRDOCTONFCE - TBMFLDOCTOFISCAL.VLRDOCTOFISCAL),0) DIF_PDV_ABC,
NVL((TBMFLDOCTOFISCAL.VLRDOCTOFISCAL - nvl(TBFISCAL.VLRFISCAL, 0) - nvl(TBFISCALAUX.VLRFISCAL, 0)),0) DIF_ABC_FISCAL,
NVL((TBDOCTONFCE.VLRDOCTONFCE - TBTESOURARIA.Vlr_Tesouraria),0) DIF_PDV_TES

FROM

(SELECT A.NROEMPRESA,
A.DTAMOVIMENTO,
count(a.numerodf) totaldocpdv,
SUM(C.VLRITEM + C.Vlracrescimo - c.vlrdesconto) VLRDOCTONFCE,
'PDV_DOCTO'
FROM PDV_DOCTO A, PDV_DOCTOITEM C
WHERE A.SERIEDF = 'CF'
AND A.SEQDOCTO = C.SEQDOCTO
AND A.STATUSDOCTO = 'V'
AND C.STATUSITEM = 'V'
AND A.NROEMPRESA IN (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND A.DTAMOVIMENTO  = TO_DATE('$data', 'YYYY-MM-DD')
GROUP BY A.NROEMPRESA, A.DTAMOVIMENTO ) TBDOCTONFCE,

(SELECT A.NROEMPRESA,
A.DTAMOVIMENTO,
count(a.numerodf) totaldoc,
SUM(B.VLRITEM + B.VLRACRESCIMO - B.VLRDESCONTO) VLRDOCTOFISCAL,
'SM'
FROM CONSINCO.MFL_DOCTOFISCAL A, CONSINCO.MFL_DFITEM B
WHERE A.NUMERODF = B.NUMERODF
AND A.SERIEDF = B.SERIEDF
AND A.NROSERIEECF = B.NROSERIEECF
AND A.NROEMPRESA = B.NROEMPRESA
AND A.MODELODF IN ('2D', '65')
AND A.STATUSDF = 'V'
AND B.STATUSITEM = 'V'
AND A.NROEMPRESA IN (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND A.DTAMOVIMENTO  = TO_DATE('$data', 'YYYY-MM-DD')
GROUP BY A.NROEMPRESA, A.DTAMOVIMENTO) TBMFLDOCTOFISCAL,

(SELECT A.NROEMPRESA,
A.DTAEMISSAO,
SUM(B.VLRTOTAL - B.VLRDESCONTO + B.VLRACRESCIMOS) VLRFISCAL,
'FISCAL'
FROM RF_NOTAMESTRE A, RF_NOTAITEM B
WHERE A.SEQNOTA = B.SEQNOTA
AND A.CODMODELO in ('2D','65')
AND A.codsitdoc = 0
AND A.NROEMPRESA IN (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND A.DTAEMISSAO = TO_DATE('$data', 'YYYY-MM-DD')
GROUP BY A.NROEMPRESA, A.DTAEMISSAO
UNION
SELECT A.NROEMPRESA,
A.DTAEMISSAO,
SUM(B.VLRTOTAL + B.VLRACRESCIMO) VLRFISCAL,
'FISCAL'
FROM RF_CUPOMMESTRE A, RF_CUPOMITEM B
WHERE A.SEQCUPOM = B.SEQCUPOM
AND A.NROEMPRESA IN (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND A.DTAEMISSAO  = TO_DATE('$data', 'YYYY-MM-DD')
GROUP BY A.NROEMPRESA, A.DTAEMISSAO) TBFISCAL,

(SELECT A.NROEMPRESA,
A.DTAEMISSAO,
SUM(B.VLRTOTAL - B.VLRDESCONTO + B.VLRACRESCIMOS) VLRFISCAL,
'FISCALAUX'
FROM RF_AUXNOTAMESTR A, RF_AUXNOTAITEM B
WHERE A.SEQNOTA = B.SEQNOTA
AND A.CODSITDOC = 0
AND A.CODMODELO = '65'
AND A.NROEMPRESA IN (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND A.DTAEMISSAO  = TO_DATE('$data', 'YYYY-MM-DD')
GROUP BY A.NROEMPRESA, A.DTAEMISSAO
UNION
SELECT A.NROEMPRESA,
A.DTAEMISSAO,
SUM(B.VLRTOTAL - B.VLRDESCONTO + B.VLRACRESCIMO) VLRFISCAL,
'FISCAL'
FROM RF_AUXCUPMESTRE A, RF_AUXCUPOMITEM B
WHERE A.SEQCUPOM = B.SEQCUPOM
AND A.NROEMPRESA IN (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND A.DTAEMISSAO  = TO_DATE('$data', 'YYYY-MM-DD')
GROUP BY A.NROEMPRESA, A.DTAEMISSAO) TBFISCALAUX,

(SELECT a.Nroempresa,
a.Dtamovimento,
SUM(a.Total) -
(SELECT NVL(SUM(b.Valor), 0)
FROM Fi_Tsmovtoopedetalhe b
WHERE a.Nroempresa = b.Nroempresa
AND a.Dtamovimento = b.Dtamovimento
AND b.Codmovimento IN (4, 10)) Vlr_Tesouraria
FROM Fi_Tsmovtooperador a
WHERE A.NROEMPRESA IN (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND A.DTAMOVIMENTO = TO_DATE('$data', 'YYYY-MM-DD')
GROUP BY a.Nroempresa, a.Dtamovimento) TBTESOURARIA

WHERE TBDOCTONFCE.NROEMPRESA = TBMFLDOCTOFISCAL.NROEMPRESA(+)
AND TBDOCTONFCE.DTAMOVIMENTO = TBMFLDOCTOFISCAL.DTAMOVIMENTO(+)
AND TBMFLDOCTOFISCAL.NROEMPRESA = TBFISCAL.NROEMPRESA(+)
AND TBMFLDOCTOFISCAL.DTAMOVIMENTO = TBFISCAL.DTAEMISSAO(+)
AND TBMFLDOCTOFISCAL.NROEMPRESA = TBFISCALAUX.NROEMPRESA(+)
AND TBMFLDOCTOFISCAL.DTAMOVIMENTO = TBFISCALAUX.DTAEMISSAO(+)
AND TBDOCTONFCE.NROEMPRESA = TBTESOURARIA.NROEMPRESA(+)
AND TBDOCTONFCE.DTAMOVIMENTO = TBTESOURARIA.DTAMOVIMENTO(+)
AND TBDOCTONFCE.NROEMPRESA in (SELECT NROEMPRESA from ge_empresa where NROEMPRESA < 70 )
AND TBDOCTONFCE.DTAMOVIMENTO  = TO_DATE('$data', 'YYYY-MM-DD')
ORDER BY 1,3,2")) {
        $e = oci_error($oraConn);
        throw new Exception("Erro ao preparar consulta - " . $e['message']);
    }

    if (!oci_execute($stmt)) {
        $e = oci_error($stmt);
        throw new Exception("Erro ao executar consulta - " . $e['message']);
    } else {
        $oraResponse = []; 
        while (($row = oci_fetch_assoc($stmt)) != false) {
            $oraResponse[] = $row; 
        }
        header('Content-Type: application/json');
        echo json_encode(array_values($oraResponse)); 
    }
} catch (Exception $e) {
    echo $e->getMessage();
    die("ERRO! Detalhes => " . $e->getMessage());
} finally {
    oci_close($oraConn); 
}
?>