#! /bin/bash
#

stty -isig
clear
echo " Informe o nome do arquivo gerado na exportacao e tecle ENTER: "
echo ""
read opcao

cp /u/sistema/bigmais/sist/trb/$opcao /u/sist/trb/$opcao

if [ $? != 1 ]
   then
   echo ""
   echo " Arquivo copiado com SUCESSO !!! Tecle <Enter> !"
   echo ""
   read tecla
   exit 0
fi

echo ""
echo " Ocorreu ERRO. Copia nao realizada !!! Tecle <Enter> !"
echo ""
read tecla
