#!/bin/bash

menu() {
while
    clear
    tput cup 7 17; tput smso; echo "Utilitario de Criacao de Usuarios Linux Avanco"; tput rmso
    tput cup 9 27; echo "1 - Criar Usuario CPD"
    tput cup 10 27; echo "2 - Criar Usuario GERAL"
    tput cup 11 27; echo "3 - Altera Senha Usuario"
    tput cup 12 27; echo "4 - Remover um Usuario"
    tput cup 13 27; echo "10 - Sair"
do
    tput cup 15 24; echo -n "Informe a Opcao => "
    read opcao
    case $opcao in
	1) criausercpd;;
	2) criausergeral;;
	3) alterasenha;;
	4) removeuser;;
	10) clear; echo ""; echo "Rotina Finalizada!"; echo ""; exit;;
    esac
done
}

criausercpd() {
while
    echo ""
do
    clear
    tput cup 0 70; tput smso; echo "10 - Volta"; tput rmso
    tput cup 7 36; tput smso; echo "Perfil CPD"; tput rmso
    tput cup 12 16; echo -n "Informe o nome do Usuario =>  "
    read usuariocpd
    case $usuariocpd in
	"") clear; echo ""; tput cup 12 30; tput smso; echo "Usuario nao informado"; tput rmso; sleep 2; criausercpd;;
	10) menu;;
	$usuariocpd)
	    testaexiste=`more /etc/passwd | grep -c $usuariocpd`
	    if [ $testaexiste -ne 0 ]; then
		clear
		echo "Este Usuario Ja' Existe"
		sleep 2
		criausercpd
	    else
	        tput cup 13 15; echo -n "Informe a senha do Usuario =>  "
	        read senhausuariocpd
		useradd -g100 $usuariocpd -d /u/login/cpd -s /bin/bash
		echo $usuariocpd:$senhausuariocpd | chpasswd
		clear
		tput cup 12 27; tput smso; echo "Usuario Criado com Sucesso!"; tput rmso
		sleep 2
		menu
	    fi
    esac
done
}

criausergeral() {
while
    echo ""
do
    clear
    tput cup 0 70; tput smso; echo "10 - Volta"; tput rmso
    tput cup 7 34; tput smso; echo "Perfil Geral"; tput rmso
    tput cup 12 16; echo -n "Informe o nome do Usuario =>  "
    read usuariogeral
    case $usuariogeral in
	"") clear; echo ""; tput cup 12 30; tput smso; echo "Usuario nao informado"; tput rmso; sleep 2; criausercpd;;
	10) menu;;
	$usuariogeral)
	    testaexiste=`more /etc/passwd | grep -c $usuariogeral`
	    if [ $testaexiste -ne 0 ]; then
		clear
		echo "Este Usuario Ja' Existe"
		sleep 2
		criausergeral
	    else
	        tput cup 13 15; echo -n "Informe a senha do Usuario =>  "
	        read senhausuariogeral
		useradd -g100 $usuariogeral -d /u/login/geral -s /bin/bash
		echo $usuariogeral:$senhausuariogeral | chpasswd
		clear
		tput cup 12 27; tput smso; echo "Usuario Criado com Sucesso!"; tput rmso
		sleep 2
		menu
	    fi
    esac
done
}

alterasenha() {
while
    echo ""
do
    clear
    tput cup 0 70; tput smso; echo "10 - Volta"; tput rmso
    tput cup 7 34; tput smso; echo "Altera Senha"; tput rmso
    tput cup 12 16; echo -n "Informe o nome do Usuario =>  "
    read pwduser
    case $pwduser in
	"") clear; echo ""; tput cup 12 30; tput smso; echo "Usuario nao informado"; tput rmso; sleep 2; criausercpd;;
	10) menu;;
	$pwduser)
	    testaexiste=`more /etc/passwd | grep -c $pwduser`
	    if [ $testaexiste = 0 ]; then
		clear
		echo "Este Usuario nAo Existe"
		sleep 2
		alterasenha
	    else
	        tput cup 13 15; echo -n "Informe a senha do Usuario =>  "
	        read senhapwduser
		echo $pwduser:$senhapwduser | chpasswd
		clear
		tput cup 12 27; tput smso; echo "Senha Alterada com Sucesso!"; tput rmso
		sleep 2
		menu
	    fi
    esac
done
}

removeuser () {
while
    clear
    tput cup 0 70; tput smso; echo "10 - Volta"; tput rmso
    tput cup 7 33; tput smso; echo "Remove Usuarios"; tput rmso
    tput cup 10 20; echo "Informe o Nome do Usuario a ser removido"
do
    tput cup 11 28;echo -n "Usuario => "; read rmuser
	case $rmuser in
	    "")	
		clear
		tput cup 12 27;tput smso; echo "Usuario nao Informado!";tput rmso
		sleep 2
		menu;;
	    10) menu;;
	    $rmuser)
		testa=`more /etc/passwd | grep -c $rmuser` 
		if [ $testa = 0 ]; then
		    clear
		    tput cup 12 29; tput smso; echo "Usuario nao cadastrado"; tput rmso
		    sleep 2
		    menu
		else
		    userdel $rmuser
		    clear
		    tput cup 12 26; tput smso; echo "Usuario removido com sucesso!"; tput rmso
		    sleep 2
		    menu
		fi;;
	esac
done
}

if [ $USER = root ]; then
    menu
else
    clear
    echo ""
    echo "Rotina exclusiva para usuArio root"
    echo ""
    exit
fi
    