#! /bin/bash
#

PNUM=`ps ax | grep rts32 | grep integ034 | cut -d' ' -f 1`
if [ ! -z "${PNUM}" ]
   then
   kill -15 ${PNUM}
fi
sleep 2
PNUM=`ps ax | grep rts32 | grep integ034 | cut -d' ' -f 1`
if [ ! -z "${PNUM}" ]
   then
   kill -9 ${PNUM}
fi
exit 0
